'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.CodeDom.Compiler
Imports System.ComponentModel
Imports System.ComponentModel.Design
Imports System.Configuration
Imports System.Runtime.CompilerServices

Namespace My
    
    <CompilerGenerated(),  _
     GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0"),  _
     EditorBrowsable(EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <DebuggerNonUserCode(), EditorBrowsable(EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Object, ByVal e As EventArgs)
        If Application.SaveMySettingsOnExit Then
            Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <UserScopedSetting(),  _
         DebuggerNonUserCode(),  _
         DefaultSettingValue("False")>  _
        Public Property debugMode() As Boolean
            Get
                Return CType(Me("debugMode"),Boolean)
            End Get
            Set
                Me("debugMode") = value
            End Set
        End Property
        
        <UserScopedSetting(),  _
         DebuggerNonUserCode(),  _
         DefaultSettingValue("1")>  _
        Public Property speed() As Integer
            Get
                Return CType(Me("speed"),Integer)
            End Get
            Set
                Me("speed") = value
            End Set
        End Property
        
        <ApplicationScopedSetting(),  _
         DebuggerNonUserCode(),  _
         SpecialSetting(SpecialSetting.ConnectionString),  _
         DefaultSettingValue("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=|DataDirectory|\ScoreDB.mdb")>  _
        Public ReadOnly Property ScoreDBConnectionString() As String
            Get
                Return CType(Me("ScoreDBConnectionString"),String)
            End Get
        End Property
        
        <UserScopedSetting(),  _
         DebuggerNonUserCode(),  _
         DefaultSettingValue("0")>  _
        Public Property currentScore() As Integer
            Get
                Return CType(Me("currentScore"),Integer)
            End Get
            Set
                Me("currentScore") = value
            End Set
        End Property
        
        <UserScopedSetting(),  _
         DebuggerNonUserCode(),  _
         DefaultSettingValue("5")>  _
        Public Property enemySpeed() As Integer
            Get
                Return CType(Me("enemySpeed"),Integer)
            End Get
            Set
                Me("enemySpeed") = value
            End Set
        End Property
        
        <UserScopedSetting(),  _
         DebuggerNonUserCode(),  _
         DefaultSettingValue("20")>  _
        Public Property reloadSpeed() As Integer
            Get
                Return CType(Me("reloadSpeed"),Integer)
            End Get
            Set
                Me("reloadSpeed") = value
            End Set
        End Property
        
        <UserScopedSetting(),  _
         DebuggerNonUserCode(),  _
         DefaultSettingValue("2")>  _
        Public Property spawnRate() As Integer
            Get
                Return CType(Me("spawnRate"),Integer)
            End Get
            Set
                Me("spawnRate") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <HideModuleName(),  _
     DebuggerNonUserCode(),  _
     CompilerGenerated()>  _
    Friend Module MySettingsProperty
        
        <HelpKeyword("My.Settings")>  _
        Friend ReadOnly Property Settings() As MySettings
            Get
                Return MySettings.Default
            End Get
        End Property
    End Module
End Namespace
